### PR TITLE
Make checksum command operating system based

### LINKED ISSUE #124: sha256sum command is "shasum -a256" on macOS
What are the steps to reproduce this issue?
-------------------------------------------
1. `brew pull https://github.com/Homebrew/homebrew-core/pull/22177`
2. `brew install -s git-secret`
3. `brew test -v git-secret`

What happens?
-------------
```
==> /usr/local/opt/gnupg/bin/gpg --batch --gen-key batch.gpg
gpg: directory '/tmp/git-secret-test-20171228-38697-hdc0f5/.gnupg' created
gpg: keybox '/tmp/git-secret-test-20171228-38697-hdc0f5/.gnupg/pubring.kbx' created
gpg: /tmp/git-secret-test-20171228-38697-hdc0f5/.gnupg/trustdb.gpg: trustdb created
gpg: key 0B593FC47C08BFBC marked as ultimately trusted
gpg: directory '/tmp/git-secret-test-20171228-38697-hdc0f5/.gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/tmp/git-secret-test-20171228-38697-hdc0f5/.gnupg/openpgp-revocs.d/3C2FDE6568107A87A54959AA0B593FC47C08BFBC.rev'
==> git init
Initialized empty Git repository in /private/tmp/git-secret-test-20171228-38697-hdc0f5/.git/
==> git config user.email testing@foo.bar
==> git secret init
'/private/tmp/git-secret-test-20171228-38697-hdc0f5/.gitsecret/' created.
cleaning up...
==> git secret tell -m
gpg: keybox '/private/tmp/git-secret-test-20171228-38697-hdc0f5/.gitsecret/keys/pubring.kbx' created
gpg: /private/tmp/git-secret-test-20171228-38697-hdc0f5/.gitsecret/keys/trustdb.gpg: trustdb created
==> git secret add shh.txt
1 item(s) added.
==> git secret hide
/usr/local/bin/git-secret: line 895: sha256sum: command not found
done. all 1 files are hidden.
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
Test::Unit::AssertionFailedError: <#<Pathname:/tmp/git-secret-test-20171228-38697-hdc0f5/shh.txt.secret>>.exist? is true value expected but was
<false>
```

What were you expecting to happen?
----------------------------------
The test to pass.

Any other comments?
-------------------
macOS has `shasum -a256` not `sha256sum`

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …
```
iMac-TMP:~ joe$ uname -a
Darwin iMac-TMP.local 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64
```

**`git-secret` path:** (`which git-secret`) …
```
iMac-TMP:~ joe$ which git-secret
/usr/local/bin/git-secret
```

**`git-secret` version:** (`git secret --version`) …
0.2.3 though it reports as 0.2.2 because version.sh wasn't updated https://github.com/sobolevn/git-secret/blob/v0.2.3/src/version.sh#L4

**`git` version:** (`git --version`) …
```
iMac-TMP:~ joe$ git --version
git version 2.15.1
```

**Shell type and version:** (`$SHELL --version`) …
```
iMac-TMP:~ joe$ $SHELL --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**`gpg` version:** (`gpg --version`) …
```
iMac-TMP:~ joe$ gpg --version
gpg (GnuPG) 2.2.4
libgcrypt 1.8.2
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/joe/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

### PR DESCRIPTION
**Pull request by ilovezfs**
Fixes #124.

### CODE REVIEW

File: src/_utils/_git_secret_tools_osx.sh [hunk 1]
```diff
@@ -13,3 +13,8 @@ function __temp_file_osx {
   filename=$(mktemp -t _gitsecrets_XXX )
   echo "$filename";
 }
+
+
+function __sha256_osx {
+  /usr/bin/shasum -a256 "$1"
```
Comment (sobolevn) [inline src/_utils/_git_secret_tools_osx.sh]: Do we really need `/usr/bin` part here?

Comment (ilovezfs) [reply src/_utils/_git_secret_tools_osx.sh]: It's somewhat safer because the path to the system `shasum` is not in doubt on macOS, so any other random `shasum` would almost certainly be undesirable.

Comment (ilovezfs) [reply src/_utils/_git_secret_tools_osx.sh]:
```
Josephs-MacBook-Pro:~ joe$ mdutil -t `which shasum`
/usr/local/Cellar/perl/5.26.1/bin/shasum
Josephs-MacBook-Pro:~ joe$ 
```
That is definitely not what you'd want to be using.

Comment (ilovezfs) [reply src/_utils/_git_secret_tools_osx.sh]: To be clear `mdutil -t` is just a cheat for `realpath`, which macOS doesn't have.
```
Josephs-MacBook-Pro:~ joe$ which shasum
/usr/local/bin/shasum
```

Comment (sobolevn) [reply src/_utils/_git_secret_tools_osx.sh]: What's the difference between them? I am concerned about it, because we don't have any other absolute paths.

Comment (ilovezfs) [reply src/_utils/_git_secret_tools_osx.sh]: The /usr/local/bin/shasum is provided by Homebrew's perl, not provided by the system, and is subject to breakage if the user's perl installation happens to be messed up. See https://github.com/Homebrew/brew/issues/3281 for the nightmares it can bring to your life.

Comment (ilovezfs) [reply src/_utils/_git_secret_tools_osx.sh]: We ended up using the absolute path as of https://github.com/Homebrew/brew/pull/3330 because random issues with non-system `shasum` kept coming up.

Comment (sobolevn) [reply src/_utils/_git_secret_tools_osx.sh]: Ok, it makes sense. Thanks!

Comment (ilovezfs) [reply src/_utils/_git_secret_tools_osx.sh]: You're welcome!

**Comment by ilovezfs** [comment]
Thanks for the merge @sobolevn!
